# This file is a part of the UMSKT Project
#
# Copyleft (C) 2019-2024 UMSKT Contributors (et.al.)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# @FileCreated by techguy16 on 07/23/2023
# @Maintainer techguy16

name: C/C++ CI (macOS)

on:
  push:
    branches: [ "*" ]
    paths-ignore: [ '**.md', 'doc/**', '.idea/**' ] # If only these files are edited, skip
  pull_request:
    branches: [ "*" ]
    paths-ignore: [ '**.md', 'doc/**', '.idea/**' ] # If only these files are edited, skip
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - { name: arm64;x86_64, displayName: all-x86_64_arm64 }
          - { name: x86_64, displayName: x86_64 }
          - { name: arm64, displayName: arm64 }
    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v4.1.1

      - name: Set up CPM cache
        id: cache-cpm
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.cpm-cache
          key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
          restore-keys: |
            ${{ runner.os }}-cpm-

      - name: Configure and build UMSKT for ${{ matrix.arch.displayName }}
        uses: threeal/cmake-action@v1.3.0
        with:
          options: MUSL_STATIC=ON CMAKE_BUILD_TYPE=Release CPM_SOURCE_CACHE=${{ github.workspace }}/.cpm-cache CMAKE_OSX_ARCHITECTURES=${{ matrix.arch.name }} BUILD_TESTING=On
          run-build: true
          build-args: -j 2
          run-test: true

      - name: Move files to correct directory
        run: |
          mkdir -p build/actions_upload
          mv build/umskt build/actions_upload/umskt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: UMSKT-macOS-${{ matrix.arch.displayName }}
          path: build/actions_upload
